apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: httpd-deploy
  name: httpd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: httpd-deploy
    spec:
      volumes:
      - name: root-dir
        persistentVolumeClaim:
          claimName: httpd-pvc
      containers:
      - image: httpd
        name: httpd
        volumeMounts:
        - name: root-dir
          mountPath: /usr/local/apache2/htdocs/
        resources: {}
status: {}
