apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: httpd-deploy
  name: httpd-deploy
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30010
  selector:
    app: httpd-deploy
  type: NodePort
status:
  loadBalancer: {}
