---
# MOODLE DEPLOYMENT
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: moodle
  name: moodle
spec:
  selector:
    matchLabels:
      app: moodle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: moodle
    spec:
      volumes:
      - name: moodle-vol
        persistentVolumeClaim:
          claimName: moodle-pvc
      - name: moodle-html-vol
        persistentVolumeClaim:
          claimName: moodle-html-pvc
      containers:
      - image: docker.io/bitnami/moodle:3
        name: moodle-pod
        envFrom:
        - secretRef:
            name: moodle-secret
        ports:
        - containerPort: 8080
        - containerPort: 8443
        volumeMounts:
        - mountPath: "/bitnami/moodledata"
          name: moodle-vol
        - mountPath: "/bitnami/moodle"
          name: moodle-html-vol
---
# MOODLE NODEPORT SVC
apiVersion: v1
kind: Service
metadata:
  name: moodle
spec:
  type: NodePort
  selector:
    app: moodle
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30010
