---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: moodle-pv
  labels:
    app: moodle-data
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 172.31.21.204
    path: "/nfs/data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: moodle-pvc
spec:
  selector:
    matchLabels:
      app: moodle-data
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
